"""
Django settings template for Melodramatick sub-project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import os.path
from pathlib import Path

from melodramatick.settings import *  # noqa: F401, F403
from melodramatick.settings import INSTALLED_APPS as IMPORTED_APPS
from melodramatick.settings import ALLOWED_HOSTS, DATABASES, DEVELOPMENT_MODE  # , TEMPLATES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS.extend(["vm", "127.0.0.1"])

#  Application definition

INSTALLED_APPS = ['<WORK_APP>'] + IMPORTED_APPS

ROOT_URLCONF = '<PROJECT>.urls'

# >>> Uncomment if you want to include base level templates >>>
# TEMPLATES[0]['DIRS'].extend([BASE_DIR / "templates"])

WSGI_APPLICATION = '<PROJECT>.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if DEVELOPMENT_MODE is True:
    DATABASES['default']['NAME'] = BASE_DIR / 'db.sqlite3'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Site-specific settings

WORK_PLURAL_LABEL = '<LABEL>'

SITE = '<PROJECT_TITLE>'
BACKGROUND_COLOUR = "<COLOUR_HEX>"


# Anything else...
