"""
Django settings for balletick project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from melodramatick.settings import *  # noqa: F401, F403
from melodramatick.settings import INSTALLED_APPS as IMPORTED_APPS
from melodramatick.settings import BASE_DIR, ALLOWED_HOSTS, TEMPLATES, STATICFILES_DIRS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS.extend(["vm", "127.0.0.1", "balletick"])


#  Application definition

INSTALLED_APPS = ['balletick'] + IMPORTED_APPS

# ROOT_URLCONF = 'balletick.urls'

TEMPLATES[0]['DIRS'].extend([BASE_DIR / "balletick" / "templates"])

# WSGI_APPLICATION = 'balletick.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# if DEVELOPMENT_MODE is True:
#     DATABASES['default']['NAME'] = BASE_DIR / 'db.sqlite3'


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/3.2/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / "balletick" / "static"] + STATICFILES_DIRS

# Site-specific settings

WORK_MODEL = 'balletick.Ballet'
WORK_PLURAL_LABEL = 'ballets'

SITE = 'Balletick'
BACKGROUND_COLOUR = '#addde7'

SITE_ID = 2
