# Generated by Django 3.2.9 on 2023-07-27 14:03

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0003_alter_work_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballet',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work.work')),
                ('choreographer', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('work.work',),
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
