# Generated by Django 3.2.9 on 2023-08-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balletick', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballet',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='ballet',
            managers=[
            ],
        ),
    ]
