# Generated by Django 3.2.9 on 2023-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardLevel',
            fields=[
                ('rank', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=10)),
                ('color_hex', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
