# Generated by Django 3.2.9 on 2023-07-20 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('work', '0001_initial'),
        ('top_list', '0003_award_list_listitem_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_item', to='work.work'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_list.list'),
        ),
        migrations.AddField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(through='top_list.ListItem', to='work.Work'),
        ),
        migrations.AddField(
            model_name='list',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AddField(
            model_name='award',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_list.awardlevel'),
        ),
        migrations.AddField(
            model_name='award',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_list.list'),
        ),
        migrations.AddField(
            model_name='award',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.UniqueConstraint(fields=('item', 'list', 'position'), name='unique_list_item'),
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('name', 'publication'), name='unique_list'),
        ),
    ]
