# Generated by Django 3.2.9 on 2024-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='spotify_player',
            field=models.CharField(choices=[('web', 'Web player'), ('app', 'Desktop app')], default='app', max_length=3, null=True),
        ),
    ]
