# Generated by Django 3.2.9 on 2024-02-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0008_alter_work_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerto',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work.work')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('work.work',),
        ),
    ]
