# Generated by Django 3.2.9 on 2024-02-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertantick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerto',
            name='instrument',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
