# Generated by Django 3.2.9 on 2024-02-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertantick', '0002_concerto_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerto',
            name='instrument',
            field=models.CharField(blank=True, choices=[('piano', 'Piano')], default='piano', max_length=10),
            preserve_default=False,
        ),
    ]
