# Generated by Django 3.2.9 on 2024-02-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertantick', '0003_alter_concerto_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerto',
            name='instrument',
            field=models.CharField(blank=True, choices=[('bassoon', 'Bassoon'), ('piano', 'Piano'), ('violin', 'Violin')], max_length=10),
        ),
    ]
