# Generated by Django 3.2.9 on 2023-07-20 10:30

from django.conf import settings
import django.contrib.sites.managers
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('duration', models.IntegerField(default=0)),
                ('id', models.CharField(max_length=220, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z0-9]{22}[,]?)+$')])),
                ('uri', models.CharField(max_length=220)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Listen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally', models.PositiveSmallIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listens',
                'verbose_name_plural': 'Listens',
            },
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
