# Generated by Django 3.2.9 on 2023-07-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('work', '0001_initial'),
        ('listen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listen',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen', to='work.work'),
        ),
        migrations.AddField(
            model_name='album',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AddField(
            model_name='album',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='work.work'),
        ),
        migrations.AddConstraint(
            model_name='listen',
            constraint=models.UniqueConstraint(fields=('work', 'user'), name='unique_listen'),
        ),
    ]
