# Generated by Django 3.2.9 on 2023-07-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='listen',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='site',
        ),
        migrations.RemoveField(
            model_name='listen',
            name='site',
        ),
    ]
