# Generated by Django 3.2.9 on 2023-09-22 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0003_auto_20230720_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listen',
            options={'ordering': ['updated_at'], 'verbose_name': 'Listens', 'verbose_name_plural': 'Listens'},
        ),
        migrations.AddField(
            model_name='listen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
