# Generated by Django 3.2.9 on 2023-09-22 15:50

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('listen', '0004_auto_20230922_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listen',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Listens', 'verbose_name_plural': 'Listens'},
        ),
        migrations.AlterModelManagers(
            name='listen',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='listen',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
            preserve_default=False,
        ),
    ]
