# Generated by Django 3.2.9 on 2024-02-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0005_auto_20230922_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
