# Generated by Django 3.2.9 on 2024-02-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0006_album_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uri',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
