# Generated by Django 3.2.9 on 2024-02-29 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0007_alter_album_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(editable=False, max_length=220, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z0-9]{22}[,]?)+$')]),
        ),
    ]
