# Generated by Django 3.2.9 on 2023-07-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('composer', 'title'), name='unique_work'),
        ),
    ]
