# Generated by Django 3.2.9 on 2023-07-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_unique_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
