# Generated by Django 3.2.9 on 2023-07-28 08:58

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('work', '0003_alter_work_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='genre',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subgenre',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgenre',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
            preserve_default=False,
        ),
    ]
