# Generated by Django 3.2.9 on 2023-08-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('work', '0004_auto_20230728_0858'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='work',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_work.work_set+', to='contenttypes.contenttype'),
        ),
    ]
