# Generated by Django 3.2.9 on 2023-11-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20230802_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_genre', to='work.genre'),
        ),
    ]
