# Generated by Django 3.2.9 on 2023-12-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_subgenre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='sub_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.subgenre'),
        ),
    ]
