# Generated by Django 3.2.9 on 2024-03-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_alter_work_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work.genre'),
        ),
        migrations.AlterField(
            model_name='work',
            name='sub_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work.subgenre'),
        ),
    ]
