# Generated by Django 3.2.9 on 2023-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0001_initial'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='work',
            field=models.ManyToManyField(related_name='performance', to='work.Work'),
        ),
    ]
