# Generated by Django 3.2.9 on 2023-07-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_performance_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='company',
        ),
    ]
