# Generated by Django 3.2.9 on 2023-07-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_remove_performance_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.company'),
        ),
    ]
