# Generated by Django 3.2.9 on 2023-07-20 10:30

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=20)),
                ('complete', models.BooleanField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('sites', models.ManyToManyField(to='sites.Site')),
            ],
            options={
                'ordering': ['surname'],
            },
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=500)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composer.composer')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('composer', models.ManyToManyField(related_name='group', to='composer.Composer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='composer',
            constraint=models.UniqueConstraint(fields=('surname', 'first_name'), name='unique_composer'),
        ),
    ]
