# Generated by Django 3.2.9 on 2023-09-29 13:33

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('composer', '0002_auto_20230929_1252'), ('composer', '0003_auto_20230929_1315')]

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('composer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SiteComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitecomplete', to='composer.composer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
