# Generated by Django 3.2.9 on 2023-09-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0002_auto_20230929_1252_squashed_0003_auto_20230929_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='complete',
        ),
    ]
