# Generated by Django 3.2.9 on 2023-10-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0003_remove_composer_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecomplete',
            options={'verbose_name_plural': 'Site complete'},
        ),
        migrations.AddConstraint(
            model_name='sitecomplete',
            constraint=models.UniqueConstraint(fields=('composer', 'site'), name='unique_sitecomplete'),
        ),
    ]
