# Generated by Django 3.2.9 on 2024-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0004_auto_20231003_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
