name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: Set up Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: "4.x"
    - run: redis-cli ping
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'dummy_melodramatick'
        mysql root password: '123abc'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run Tests
      run: |
        DJANGO_SETTINGS_MODULE=operatick.settings coverage run --source='.' manage.py test
        coverage xml
    - name: Get coverage
      uses: orgoro/coverage@v3.1
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'pull_request'
